require: rubocop

Documentation:
    Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/HashEachMethods:
    Enabled: false
Style/HashTransformKeys:
    Enabled: false
Style/HashTransformValues:
    Enabled: false

Layout/EmptyLinesAroundClassBody:
    Enabled: false
Lint/AssignmentInCondition:
    Enabled: false
Layout/DefEndAlignment:
    Enabled: false

Lint/AmbiguousOperator:
    Enabled: false
